version: '3.8'

services:
  todolist-mycontainer:
    container_name: todolist-mycontainer
    build: 
      context: .
      dockerfile: dockerfile
    restart: always
    image: alwi09/todolist-image:v1
    ports:
      - "1234:1234"
    depends_on:
      - mysql-mycontainer
    networks:
      - network-todolist
    links:
      - mysql-mycontainer
  mysql-mycontainer:
    container_name: mysql-mycontainer
    image: mysql:8.0.33
    ports:
      - "3300:3306"
    environment:
      - MYSQL_USER=alwi09
      - MYSQL_PASSWORD=alwiirfani091199
      - MYSQL_ROOT_PASSWORD=alwiirfani091199
      - MYSQL_DATABASE=todolist_restfulapi
    networks:
      - network-todolist

networks:
  network-todolist:
    name: network-todolist
    driver: bridge
