// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// CreateHandlerTodolist provides a mock function with given fields: ctx
func (_m *Handler) CreateHandlerTodolist(ctx *gin.Context) {
	_m.Called(ctx)
}

// DeleteHandlerTodolist provides a mock function with given fields: ctx
func (_m *Handler) DeleteHandlerTodolist(ctx *gin.Context) {
	_m.Called(ctx)
}

// GetAllHandlerTodolist provides a mock function with given fields: ctx
func (_m *Handler) GetAllHandlerTodolist(ctx *gin.Context) {
	_m.Called(ctx)
}

// GetIDHandlerTodolist provides a mock function with given fields: ctx
func (_m *Handler) GetIDHandlerTodolist(ctx *gin.Context) {
	_m.Called(ctx)
}

// UpdateHandlerTodolist provides a mock function with given fields: ctx
func (_m *Handler) UpdateHandlerTodolist(ctx *gin.Context) {
	_m.Called(ctx)
}

type mockConstructorTestingTNewHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewHandler creates a new instance of Handler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHandler(t mockConstructorTestingTNewHandler) *Handler {
	mock := &Handler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
